services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    init: true
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055
    volumes:
      - seerr-config:/app/config
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "seerr"
    restart: always

volumes:
  seerr-config:
