services:
  nessus:
    image: docker.io/tenable/nessus:latest-ubuntu
    container_name: nessus
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "nessus"
      tsdproxy.port.1: "443/https:8834/http"
    restart: always
