services:
  requestrr:
    image: darkalfx/requestrr:latest
    container_name: requestrr
    environment:
      - TZ=${TZ}
    volumes:
      - requestrr-config:/root/config
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "requestrr"
      tsdproxy.port.1: "443/https:4200/http"
    restart: always

volumes:
  requestrr-config:
