services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    environment:
      - TZ=${TZ}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
    volumes:
      - gotify-data:/app/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "gotify"
      tsdproxy.port.1: "443/https:80/http"
    restart: always

volumes:
  gotify-data:
