services:
  dockhand:
    image: docker.io/fnsys/dockhand:latest
    container_name: dockhand
    environment:
      - TZ=${TZ}
      - HOST_DATA_DIR=/app/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand-data:/app/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "dockhand"
    restart: always

volumes:
  dockhand-data:
