services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    environment:
      - TZ=${TZ}
      - SECRET=change-me-please-secret
      - APP_URL=${TINYAUTH_APP_URL}
      - USERS=${TINYAUTH_USERS}
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "tinyauth"
    restart: always
