services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    environment:
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}
    volumes:
      - n8n-data:/home/node/.n8n
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "n8n"
      tsdproxy.port.1: "443/https:5678/http"
    restart: always

volumes:
  n8n-data:
