services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${TZ}
    user: "1000:1000"
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-etc:/etc/ntfy
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "ntfy"
      tsdproxy.port.1: "443/https:80/http"
    restart: always

volumes:
  ntfy-cache:
  ntfy-etc:
