services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - linkding-data:/etc/linkding/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "linkding"
      tsdproxy.port.1: "443/https:9090/http"
    restart: always

volumes:
  linkding-data:
