services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    environment:
      - TZ=${TZ}
      - APP_URL=${APP_URL}
      - ENCRYPTION_KEY=${ARCANE_ENCRYPTION_KEY}
      - JWT_SECRET=${ARCANE_JWT_SECRET}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - OIDC_ENABLED=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "arcane"
      tsdproxy.port.1: "443/https:8080/http"
    restart: always

volumes:
  arcane-data:
