services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    environment:
      - TZ=${TZ}
    volumes:
      - adguardhome-work:/opt/adguardhome/work
      - adguardhome-conf:/opt/adguardhome/conf
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "adguardhome"
      tsdproxy.port.1: "443/https:80/http"
    restart: always

volumes:
  adguardhome-work:
  adguardhome-conf:
