services:
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine-migration:
        condition: service_completed_successfully
    volumes:
      - affine-storage:/root/.affine/storage
      - affine-config:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://affine:affine_secure_pass@postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false
      - AFFINE_SERVER_EXTERNAL_URL=${AFFINE_SERVER_EXTERNAL_URL}
      - TZ=${TZ}
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "affine"
      tsdproxy.port.1: "443/https:3000/http"
    restart: always

  affine-migration:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine-migration
    volumes:
      - affine-storage:/root/.affine/storage
      - affine-config:/root/.affine/config
    command: [ 'sh', '-c', 'node ./scripts/self-host-predeploy.js' ]
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://affine:affine_secure_pass@postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false
      - AFFINE_SERVER_EXTERNAL_URL=${AFFINE_SERVER_EXTERNAL_URL}
      - TZ=${TZ}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: affine-redis
    environment:
      - TZ=${TZ}
    healthcheck:
      test: [ 'CMD', 'redis-cli', '--raw', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine-postgres
    volumes:
      - affine-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=affine
      - POSTGRES_PASSWORD=affine_secure_pass
      - POSTGRES_DB=affine
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=${TZ}
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', "affine", '-d', "affine" ]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  affine-storage:
  affine-config:
  affine-postgres:
