services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - code-server-config:/config
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "code-server"
      tsdproxy.port.1: "443/https:8443/https"
    restart: always

volumes:
  code-server-config:
