services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - nextcloud-config:/config
      - nextcloud-data:/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "nextcloud"
      tsdproxy.port.1: "443/https:443/https"
    restart: always

volumes:
  nextcloud-config:
  nextcloud-data:
