services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - navidrome-data:/data
      - navidrome-music:/music:ro
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "navidrome"
      tsdproxy.port.1: "443/https:4533/http"
    restart: always

volumes:
  navidrome-data:
  navidrome-music:
