services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - dozzle-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "dozzle"
    restart: always

volumes:
  dozzle-data:
