services:
  haptic:
    image: chroxify/haptic-web:latest
    container_name: haptic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "haptic"
      tsdproxy.port.1: "443/https:3000/http"
    restart: always
