services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - duplicati-config:/config
      - ${DATA_DIR}:/source
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "duplicati"
      tsdproxy.port.1: "443/https:8200/http"
    restart: always

volumes:
  duplicati-config:
