services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FILEBROWSER_USERNAME=${FILEBROWSER_USERNAME}
      - FILEBROWSER_PASSWORD=${FILEBROWSER_PASSWORD}
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    entrypoint: ["/bin/sh"]
    command:
      - -c
      - if [ ! -f /database/filebrowser.db ]; then filebrowser -d /database/filebrowser.db -c /config/settings.json config init --address 0.0.0.0 --port 80 --root /srv --minimumPasswordLength 1 || exit 1; fi; filebrowser -d /database/filebrowser.db -c /config/settings.json config set --address 0.0.0.0 --port 80 --root /srv --minimumPasswordLength 1 || exit 1; filebrowser -d /database/filebrowser.db -c /config/settings.json users update 1 --username "$$FILEBROWSER_USERNAME" --password "$$FILEBROWSER_PASSWORD" --perm.admin --scope / || filebrowser -d /database/filebrowser.db -c /config/settings.json users add "$$FILEBROWSER_USERNAME" "$$FILEBROWSER_PASSWORD" --perm.admin --scope / || exit 1; exec filebrowser -d /database/filebrowser.db -c /config/settings.json --address 0.0.0.0 --port 80 --root /srv
    volumes:
      - filebrowser-db:/database
      - filebrowser-config:/config
      - ${DATA_DIR}:/srv
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "filebrowser"
      tsdproxy.port.1: "443/https:80/http"
    restart: always

volumes:
  filebrowser-db:
  filebrowser-config:
