services:
  configarr:
    image: ghcr.io/raydak-labs/configarr:latest
    container_name: configarr
    environment:
      - TZ=${TZ}
    volumes:
      - configarr-config:/app/config
      - configarr-repos:/app/repos
    restart: "no"

volumes:
  configarr-config:
  configarr-repos:
