services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DB_CONNECTION=sqlite
    volumes:
      - speedtest-tracker-config:/config
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "speedtest-tracker"
    restart: always

volumes:
  speedtest-tracker-config:
