services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: ghost_root_db_pass
      database__connection__database: ghost
      url: http://localhost:2368
    volumes:
      - ghost-config:/config
      - ghost-content:/var/lib/ghost/content
    depends_on:
      ghost-db:
        condition: service_healthy
    restart: always
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "ghost"
      tsdproxy.port.1: "443/https:2368/http"

  ghost-db:
    image: mysql:8.0
    container_name: ghost-db
    environment:
      MYSQL_ROOT_PASSWORD: ghost_root_db_pass
      MYSQL_DATABASE: ghost
    volumes:
      - ghost-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pghost_root_db_pass"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  ghost-config:
  ghost-content:
  ghost-db-data:
