services:
  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:release
    container_name: hoarder-web
    depends_on:
      - hoarder-chrome
      - hoarder-meilisearch
    environment:
      - NEXTAUTH_SECRET=changethisnextauthsecret32chars!
      - MEILI_MASTER_KEY=changethismeilimasterkey32chars!
      - NEXTAUTH_URL=${HOARDER_NEXTAUTH_URL}
      - MEILI_ADDR=http://hoarder-meilisearch:7700
      - BROWSER_WEB_URL=http://hoarder-chrome:9222
      - DATA_DIR=/data
      - TZ=${TZ}
    volumes:
      - hoarder-data:/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "hoarder"
    restart: always

  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: hoarder-chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    environment:
      - TZ=${TZ}
    restart: always

  hoarder-meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: hoarder-meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=changethismeilimasterkey32chars!
      - TZ=${TZ}
    volumes:
      - hoarder-meili-data:/meili_data
    restart: always

volumes:
  hoarder-data:
  hoarder-meili-data:
