services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - tautulli-config:/config
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "tautulli"
      tsdproxy.port.1: "443/https:8181/http"
    restart: always

volumes:
  tautulli-config:
