services:
  wireguard:
    image: weejewel/wg-easy:latest
    container_name: wireguard
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PASSWORD=${WG_PASSWORD}
      - WG_HOST=${WG_HOST}
    ports:
      - 51820:51820/udp
    volumes:
      - wireguard-config:/etc/wireguard
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "wireguard"
      tsdproxy.port.1: "443/https:51821/http"
    restart: always

volumes:
  wireguard-config:
