services:
  beszel-hub:
    image: henrygd/beszel:latest
    container_name: beszel-hub
    environment:
      - TZ=${TZ}
    volumes:
      - beszel-hub-data:/beszel_data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "beszel"
      tsdproxy.port.1: "443/https:8090/http"
    restart: always

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    network_mode: host
    environment:
      - PORT=45876
      - KEY=${BESZEL_AGENT_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  beszel-hub-data:
