services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - audiobookshelf-config:/config
      - audiobookshelf-audiobooks:/audiobooks
      - audiobookshelf-podcasts:/podcasts
      - audiobookshelf-metadata:/metadata
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "audiobookshelf"
      tsdproxy.port.1: "443/https:13378/http"
    restart: always

volumes:
  audiobookshelf-config:
  audiobookshelf-audiobooks:
  audiobookshelf-podcasts:
  audiobookshelf-metadata:
