services:
  ddns-updater:
    image: docker.io/qmcgaw/ddns-updater:latest
    container_name: ddns-updater
    environment:
      - TZ=${TZ}
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s
      - LISTENING_ADDRESS=:8000
      - ROOT_URL=/
      - BACKUP_PERIOD=0
      - BACKUP_DIRECTORY=/updater/data
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
    volumes:
      - ddns-updater-data:/updater/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "ddns-updater"
      tsdproxy.port.1: "443/https:8080/http"
    restart: always

volumes:
  ddns-updater-data:
