services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - syncthing-config:/config
      - ${DATA_DIR}:/data1
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "syncthing"
    restart: always

volumes:
  syncthing-config:
