services:
  dumbdo:
    image: docker.io/dumbwareio/dumbdo:latest
    container_name: dumbdo
    environment:
      - TZ=${TZ}
    volumes:
      - dumbdo-data:/app/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "dumbdo"
      tsdproxy.port.1: "443/https:8080/http"
    restart: always

volumes:
  dumbdo-data:
